# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psQvlR1WhoXps5mDdz5nNjx4qV-MjGc8
"""


import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, r2_score, mean_squared_error
from xgboost import XGBClassifier
from pptx import Presentation
from pptx.util import Inches, Pt
from datetime import datetime, timedelta

# ===============================================
# 1. Coleta de dados
# ===============================================
df = yf.download("^BVSP", period="2y", interval="1d")
df.dropna(inplace=True)

# ===============================================
# 2. Engenharia de atributos
# ===============================================
df['Return'] = df['Close'].pct_change()
df['MA5'] = df['Close'].rolling(5).mean()
df['MA10'] = df['Close'].rolling(10).mean()
df['Volatility'] = df['Return'].rolling(10).std()
df.dropna(inplace=True)

# Target: 1 = Alta, 0 = Baixa
df['Target'] = (df['Close'].shift(-1) > df['Close']).astype(int)

# ===============================================
# 3. Preparação dos dados
# ===============================================
features = ['Close', 'Return', 'MA5', 'MA10', 'Volatility']
X = df[features]
y = df['Target']

# Últimos 30 pregões = teste
X_train, X_test = X.iloc[:-30], X.iloc[-30:]
y_train, y_test = y.iloc[:-30], y.iloc[-30:]

# ===============================================
# 4. Treinamento do modelo
# ===============================================
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

# ===============================================
# 5. Avaliação
# ===============================================
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Acurácia no último mês:", round(acc*100,2), "%")
print("\nRelatório de Classificação:\n", classification_report(y_test, y_pred))
print("\nMatriz de Confusão:\n", confusion_matrix(y_test, y_pred))

# Gráfico de previsões no teste
plt.figure(figsize=(12,5))
plt.plot(df.index[-30:], df['Close'].iloc[-30:], marker='o', label="Fechamento")
plt.scatter(df.index[-30:], df['Close'].iloc[-30:],
            c=y_pred, cmap='bwr', label="Previsão (Azul=Baixa, Vermelho=Alta)")
plt.title("Previsão de Tendência - Últimos 30 dias")
plt.xlabel("Data")
plt.ylabel("IBOV Fechamento")
plt.legend()
plt.grid()
plt.savefig("previsoes_teste.png")
plt.show()

# ===============================================
# 6. Projeção para os próximos 5 dias úteis
# ===============================================
projecoes = []
ultimo_dado = df.iloc[-1].copy()
hoje = df.index[-1]

for i in range(1, 6):  # próximos 5 dias
    prox_data = hoje + timedelta(days=i)
    while prox_data.weekday() >= 5:  # pula sábado/domingo
        prox_data += timedelta(days=1)

    X_input = ultimo_dado[features].values.reshape(1, -1)
    tendencia = model.predict(X_input)[0]

    projecoes.append({
        "Data": prox_data.strftime("%d/%m/%Y"),
        "Tendência": "↑ ALTA" if tendencia == 1 else "↓ BAIXA"
    })

    # atualizar para simular próximos dias (aqui mantemos valores estáticos, real seria via forecasting Close)
    ultimo_dado['Close'] *= (1 + np.random.normal(0, 0.01))  # simulação de variação
    ultimo_dado['Return'] = np.random.normal(0, 0.01)

projecoes_df = pd.DataFrame(projecoes)
print("\n📈 Projeções para os próximos dias:\n", projecoes_df)



# ===============================================
# . Modelo de Classificação
# ===============================================
clf = RandomForestClassifier(n_estimators=200, random_state=42)
clf.fit(X_train, y_train)
y_pred_class = clf.predict(X_test)

acc = accuracy_score(y_test, y_pred_class)

print("🔵 CLASSIFICAÇÃO (↑ ou ↓)")
print("Acurácia no último mês:", round(acc*100,2), "%")
print("\nRelatório de Classificação:\n", classification_report(y_test, y_pred_class))
print("\nMatriz de Confusão:\n", confusion_matrix(y_test, y_pred_class))

# Gráfico - classificação
plt.figure(figsize=(12,5))
plt.plot(df.index[-30:], df['Close'].iloc[-30:], marker='o', label="Fechamento")
plt.scatter(df.index[-30:], df['Close'].iloc[-30:],
            c=y_pred_class, cmap='bwr', label="Previsão (Azul=Baixa, Vermelho=Alta)")
plt.title("Previsão de Tendência (Classificação) - Últimos 30 dias")
plt.xlabel("Data")
plt.ylabel("IBOV Fechamento")
plt.legend()
plt.grid()
plt.savefig("previsoes_class.png")
plt.show()

# ---------- ) Preparação do conjunto de treino/teste ----------
df.dropna(inplace=True) # Remove linhas com NaN após criar todas as features

TEST_DAYS = 30
train = df.iloc[:-TEST_DAYS].copy()
test = df.iloc[-TEST_DAYS:].copy()


print(f"Tamanho treino: {len(train)}, tamanho teste: {len(test)}")


feature_cols = [
'Close', 'Return', 'MA5', 'MA10', 'Volatility' # Corrigido para as features existentes
]


X_train = train[feature_cols]
y_train = train['Target'] # Corrigido para 'Target'
X_test = test[feature_cols]
y_test = test['Target'] # Corrigido para 'Target'

# ===============================================
# . Modelo de Regressão
# ===============================================
reg = RandomForestRegressor(n_estimators=200, random_state=42)
reg.fit(X_train, train['Close'].values.ravel())
y_pred_reg = reg.predict(X_test)

r2 = r2_score(test['Close'], y_pred_reg)
rmse = np.sqrt(mean_squared_error(test['Close'], y_pred_reg))

print("\n🟢 REGRESSÃO (Preço do IBOV)")
print("R² no último mês:", round(r2,4))
print("RMSE:", round(rmse,2))

# Gráfico - regressão
plt.figure(figsize=(12,5))
plt.plot(df.index[-30:], test['Close'], label="Real", marker='o')
plt.plot(df.index[-30:], y_pred_reg, label="Previsto (Regressão)", marker='x')
plt.title("Previsão de Preço (Regressão) - Últimos 30 dias")
plt.xlabel("Data")
plt.ylabel("IBOV Fechamento")
plt.legend()
plt.grid()
plt.savefig("previsoes_reg.png")
plt.show()

import joblib
joblib.dump(reg, 'fase2.sav')